/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrgOrgSlugRouteRouteImport } from './routes/org/$orgSlug/route'
import { Route as OrgOrgSlugAiRouteImport } from './routes/org/$orgSlug/ai'
import { Route as OrgOrgSlugAuditRouteImport } from './routes/org/$orgSlug/audit'
import { Route as OrgOrgSlugDashboardRouteImport } from './routes/org/$orgSlug/dashboard'
import { Route as OrgOrgSlugFilesRouteImport } from './routes/org/$orgSlug/files'
import { Route as OrgOrgSlugMembersRouteImport } from './routes/org/$orgSlug/members'
import { Route as OrgOrgSlugAdminSettingsRouteImport } from './routes/org/$orgSlug/admin/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgSlugRouteRoute = OrgOrgSlugRouteRouteImport.update({
  id: '/org/$orgSlug',
  path: '/org/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgSlugAiRoute = OrgOrgSlugAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => OrgOrgSlugRouteRoute,
} as any)
const OrgOrgSlugAuditRoute = OrgOrgSlugAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OrgOrgSlugRouteRoute,
} as any)
const OrgOrgSlugDashboardRoute = OrgOrgSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrgOrgSlugRouteRoute,
} as any)
const OrgOrgSlugFilesRoute = OrgOrgSlugFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OrgOrgSlugRouteRoute,
} as any)
const OrgOrgSlugMembersRoute = OrgOrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgOrgSlugRouteRoute,
} as any)
const OrgOrgSlugAdminSettingsRoute = OrgOrgSlugAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => OrgOrgSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/org/$orgSlug': typeof OrgOrgSlugRouteRouteWithChildren
  '/org/$orgSlug/ai': typeof OrgOrgSlugAiRoute
  '/org/$orgSlug/audit': typeof OrgOrgSlugAuditRoute
  '/org/$orgSlug/dashboard': typeof OrgOrgSlugDashboardRoute
  '/org/$orgSlug/files': typeof OrgOrgSlugFilesRoute
  '/org/$orgSlug/members': typeof OrgOrgSlugMembersRoute
  '/org/$orgSlug/admin/settings': typeof OrgOrgSlugAdminSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/org/$orgSlug': typeof OrgOrgSlugRouteRouteWithChildren
  '/org/$orgSlug/ai': typeof OrgOrgSlugAiRoute
  '/org/$orgSlug/audit': typeof OrgOrgSlugAuditRoute
  '/org/$orgSlug/dashboard': typeof OrgOrgSlugDashboardRoute
  '/org/$orgSlug/files': typeof OrgOrgSlugFilesRoute
  '/org/$orgSlug/members': typeof OrgOrgSlugMembersRoute
  '/org/$orgSlug/admin/settings': typeof OrgOrgSlugAdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/org/$orgSlug': typeof OrgOrgSlugRouteRouteWithChildren
  '/org/$orgSlug/ai': typeof OrgOrgSlugAiRoute
  '/org/$orgSlug/audit': typeof OrgOrgSlugAuditRoute
  '/org/$orgSlug/dashboard': typeof OrgOrgSlugDashboardRoute
  '/org/$orgSlug/files': typeof OrgOrgSlugFilesRoute
  '/org/$orgSlug/members': typeof OrgOrgSlugMembersRoute
  '/org/$orgSlug/admin/settings': typeof OrgOrgSlugAdminSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/org/$orgSlug'
    | '/org/$orgSlug/ai'
    | '/org/$orgSlug/audit'
    | '/org/$orgSlug/dashboard'
    | '/org/$orgSlug/files'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/org/$orgSlug'
    | '/org/$orgSlug/ai'
    | '/org/$orgSlug/audit'
    | '/org/$orgSlug/dashboard'
    | '/org/$orgSlug/files'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/org/$orgSlug'
    | '/org/$orgSlug/ai'
    | '/org/$orgSlug/audit'
    | '/org/$orgSlug/dashboard'
    | '/org/$orgSlug/files'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug/admin/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrgOrgSlugRouteRoute: typeof OrgOrgSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgSlug': {
      id: '/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof OrgOrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgSlug/ai': {
      id: '/org/$orgSlug/ai'
      path: '/ai'
      fullPath: '/org/$orgSlug/ai'
      preLoaderRoute: typeof OrgOrgSlugAiRouteImport
      parentRoute: typeof OrgOrgSlugRouteRoute
    }
    '/org/$orgSlug/audit': {
      id: '/org/$orgSlug/audit'
      path: '/audit'
      fullPath: '/org/$orgSlug/audit'
      preLoaderRoute: typeof OrgOrgSlugAuditRouteImport
      parentRoute: typeof OrgOrgSlugRouteRoute
    }
    '/org/$orgSlug/dashboard': {
      id: '/org/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/org/$orgSlug/dashboard'
      preLoaderRoute: typeof OrgOrgSlugDashboardRouteImport
      parentRoute: typeof OrgOrgSlugRouteRoute
    }
    '/org/$orgSlug/files': {
      id: '/org/$orgSlug/files'
      path: '/files'
      fullPath: '/org/$orgSlug/files'
      preLoaderRoute: typeof OrgOrgSlugFilesRouteImport
      parentRoute: typeof OrgOrgSlugRouteRoute
    }
    '/org/$orgSlug/members': {
      id: '/org/$orgSlug/members'
      path: '/members'
      fullPath: '/org/$orgSlug/members'
      preLoaderRoute: typeof OrgOrgSlugMembersRouteImport
      parentRoute: typeof OrgOrgSlugRouteRoute
    }
    '/org/$orgSlug/admin/settings': {
      id: '/org/$orgSlug/admin/settings'
      path: '/admin/settings'
      fullPath: '/org/$orgSlug/admin/settings'
      preLoaderRoute: typeof OrgOrgSlugAdminSettingsRouteImport
      parentRoute: typeof OrgOrgSlugRouteRoute
    }
  }
}

interface OrgOrgSlugRouteRouteChildren {
  OrgOrgSlugAiRoute: typeof OrgOrgSlugAiRoute
  OrgOrgSlugAuditRoute: typeof OrgOrgSlugAuditRoute
  OrgOrgSlugDashboardRoute: typeof OrgOrgSlugDashboardRoute
  OrgOrgSlugFilesRoute: typeof OrgOrgSlugFilesRoute
  OrgOrgSlugMembersRoute: typeof OrgOrgSlugMembersRoute
  OrgOrgSlugAdminSettingsRoute: typeof OrgOrgSlugAdminSettingsRoute
}

const OrgOrgSlugRouteRouteChildren: OrgOrgSlugRouteRouteChildren = {
  OrgOrgSlugAiRoute: OrgOrgSlugAiRoute,
  OrgOrgSlugAuditRoute: OrgOrgSlugAuditRoute,
  OrgOrgSlugDashboardRoute: OrgOrgSlugDashboardRoute,
  OrgOrgSlugFilesRoute: OrgOrgSlugFilesRoute,
  OrgOrgSlugMembersRoute: OrgOrgSlugMembersRoute,
  OrgOrgSlugAdminSettingsRoute: OrgOrgSlugAdminSettingsRoute,
}

const OrgOrgSlugRouteRouteWithChildren = OrgOrgSlugRouteRoute._addFileChildren(
  OrgOrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrgOrgSlugRouteRoute: OrgOrgSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
