/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteRouteImport } from './routes/$orgSlug/route'
import { Route as CreateRouteImport } from './routes/create'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as OrgSlugDashboardRouteImport } from './routes/$orgSlug/dashboard'
import { Route as OrgSlugFilesRouteImport } from './routes/$orgSlug/files'
import { Route as OrgSlugOnboardingRouteImport } from './routes/$orgSlug/onboarding'
import { Route as OrgSlugSettingsRouteRouteImport } from './routes/$orgSlug/settings/route'
import { Route as OrgSlugBillingIndexRouteImport } from './routes/$orgSlug/billing/index'
import { Route as OrgSlugOpdIndexRouteImport } from './routes/$orgSlug/opd/index'
import { Route as OrgSlugOpdAppointmentIdRouteRouteImport } from './routes/$orgSlug/opd/$appointmentId/route'
import { Route as OrgSlugOpdNewRouteImport } from './routes/$orgSlug/opd/new'
import { Route as OrgSlugPatientsIndexRouteImport } from './routes/$orgSlug/patients/index'
import { Route as OrgSlugPatientsPatientIdRouteImport } from './routes/$orgSlug/patients/$patientId'
import { Route as OrgSlugReportsIndexRouteImport } from './routes/$orgSlug/reports/index'
import { Route as OrgSlugReportsBalanceSheetRouteImport } from './routes/$orgSlug/reports/balance-sheet'
import { Route as OrgSlugReportsDailyCollectionsRouteImport } from './routes/$orgSlug/reports/daily-collections'
import { Route as OrgSlugReportsGstRouteImport } from './routes/$orgSlug/reports/gst'
import { Route as OrgSlugReportsOpdRegisterRouteImport } from './routes/$orgSlug/reports/opd-register'
import { Route as OrgSlugReportsTrialBalanceRouteImport } from './routes/$orgSlug/reports/trial-balance'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as OrgSlugSettingsAuditRouteImport } from './routes/$orgSlug/settings/audit'
import { Route as OrgSlugSettingsCatalogRouteImport } from './routes/$orgSlug/settings/catalog'
import { Route as OrgSlugSettingsMembersRouteImport } from './routes/$orgSlug/settings/members'
import { Route as OrgSlugSettingsOrganizationRouteImport } from './routes/$orgSlug/settings/organization'
import { Route as OrgSlugSettingsStaffRouteImport } from './routes/$orgSlug/settings/staff'
import { Route as OrgSlugBillingInvoicesInvoiceIdRouteImport } from './routes/$orgSlug/billing/invoices.$invoiceId'
import { Route as OrgSlugOpdAppointmentIdIndexRouteImport } from './routes/$orgSlug/opd/$appointmentId/index'
import { Route as OrgSlugOpdAppointmentIdBillingRouteImport } from './routes/$orgSlug/opd/$appointmentId/billing'
import { Route as OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRouteImport } from './routes/$orgSlug/billing/invoices.$invoiceId.credit-note.$creditNoteId'
import { Route as OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRouteImport } from './routes/$orgSlug/billing/invoices.$invoiceId.receipt.$paymentId'
import { Route as OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRouteImport } from './routes/$orgSlug/billing/invoices.$invoiceId.refund.$refundId'
import { Route as ApiOrgSlugBillingInvoicesInvoiceIdPdfRouteImport } from './routes/api.$orgSlug.billing.invoices.$invoiceId.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugDashboardRoute = OrgSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugFilesRoute = OrgSlugFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugOnboardingRoute = OrgSlugOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugSettingsRouteRoute = OrgSlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugBillingIndexRoute = OrgSlugBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugOpdIndexRoute = OrgSlugOpdIndexRouteImport.update({
  id: '/opd/',
  path: '/opd/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugOpdAppointmentIdRouteRoute =
  OrgSlugOpdAppointmentIdRouteRouteImport.update({
    id: '/opd/$appointmentId',
    path: '/opd/$appointmentId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugOpdNewRoute = OrgSlugOpdNewRouteImport.update({
  id: '/opd/new',
  path: '/opd/new',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPatientsIndexRoute = OrgSlugPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPatientsPatientIdRoute =
  OrgSlugPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsIndexRoute = OrgSlugReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReportsBalanceSheetRoute =
  OrgSlugReportsBalanceSheetRouteImport.update({
    id: '/reports/balance-sheet',
    path: '/reports/balance-sheet',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsDailyCollectionsRoute =
  OrgSlugReportsDailyCollectionsRouteImport.update({
    id: '/reports/daily-collections',
    path: '/reports/daily-collections',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsGstRoute = OrgSlugReportsGstRouteImport.update({
  id: '/reports/gst',
  path: '/reports/gst',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReportsOpdRegisterRoute =
  OrgSlugReportsOpdRegisterRouteImport.update({
    id: '/reports/opd-register',
    path: '/reports/opd-register',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsTrialBalanceRoute =
  OrgSlugReportsTrialBalanceRouteImport.update({
    id: '/reports/trial-balance',
    path: '/reports/trial-balance',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsAuditRoute = OrgSlugSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsCatalogRoute = OrgSlugSettingsCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsMembersRoute = OrgSlugSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsOrganizationRoute =
  OrgSlugSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgSlugSettingsRouteRoute,
  } as any)
const OrgSlugSettingsStaffRoute = OrgSlugSettingsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugBillingInvoicesInvoiceIdRoute =
  OrgSlugBillingInvoicesInvoiceIdRouteImport.update({
    id: '/billing/invoices/$invoiceId',
    path: '/billing/invoices/$invoiceId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugOpdAppointmentIdIndexRoute =
  OrgSlugOpdAppointmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugOpdAppointmentIdRouteRoute,
  } as any)
const OrgSlugOpdAppointmentIdBillingRoute =
  OrgSlugOpdAppointmentIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => OrgSlugOpdAppointmentIdRouteRoute,
  } as any)
const OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute =
  OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRouteImport.update({
    id: '/credit-note/$creditNoteId',
    path: '/credit-note/$creditNoteId',
    getParentRoute: () => OrgSlugBillingInvoicesInvoiceIdRoute,
  } as any)
const OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute =
  OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRouteImport.update({
    id: '/receipt/$paymentId',
    path: '/receipt/$paymentId',
    getParentRoute: () => OrgSlugBillingInvoicesInvoiceIdRoute,
  } as any)
const OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute =
  OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRouteImport.update({
    id: '/refund/$refundId',
    path: '/refund/$refundId',
    getParentRoute: () => OrgSlugBillingInvoicesInvoiceIdRoute,
  } as any)
const ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute =
  ApiOrgSlugBillingInvoicesInvoiceIdPdfRouteImport.update({
    id: '/api/$orgSlug/billing/invoices/$invoiceId/pdf',
    path: '/api/$orgSlug/billing/invoices/$invoiceId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteRouteWithChildren
  '/$orgSlug/dashboard': typeof OrgSlugDashboardRoute
  '/$orgSlug/files': typeof OrgSlugFilesRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/opd/$appointmentId': typeof OrgSlugOpdAppointmentIdRouteRouteWithChildren
  '/$orgSlug/opd/new': typeof OrgSlugOpdNewRoute
  '/$orgSlug/patients/$patientId': typeof OrgSlugPatientsPatientIdRoute
  '/$orgSlug/reports/balance-sheet': typeof OrgSlugReportsBalanceSheetRoute
  '/$orgSlug/reports/daily-collections': typeof OrgSlugReportsDailyCollectionsRoute
  '/$orgSlug/reports/gst': typeof OrgSlugReportsGstRoute
  '/$orgSlug/reports/opd-register': typeof OrgSlugReportsOpdRegisterRoute
  '/$orgSlug/reports/trial-balance': typeof OrgSlugReportsTrialBalanceRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/catalog': typeof OrgSlugSettingsCatalogRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/staff': typeof OrgSlugSettingsStaffRoute
  '/$orgSlug/billing/': typeof OrgSlugBillingIndexRoute
  '/$orgSlug/opd/': typeof OrgSlugOpdIndexRoute
  '/$orgSlug/patients/': typeof OrgSlugPatientsIndexRoute
  '/$orgSlug/reports/': typeof OrgSlugReportsIndexRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/billing/invoices/$invoiceId': typeof OrgSlugBillingInvoicesInvoiceIdRouteWithChildren
  '/$orgSlug/opd/$appointmentId/billing': typeof OrgSlugOpdAppointmentIdBillingRoute
  '/$orgSlug/opd/$appointmentId/': typeof OrgSlugOpdAppointmentIdIndexRoute
  '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId': typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId': typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId': typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute
  '/api/$orgSlug/billing/invoices/$invoiceId/pdf': typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/$orgSlug/dashboard': typeof OrgSlugDashboardRoute
  '/$orgSlug/files': typeof OrgSlugFilesRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/opd/new': typeof OrgSlugOpdNewRoute
  '/$orgSlug/patients/$patientId': typeof OrgSlugPatientsPatientIdRoute
  '/$orgSlug/reports/balance-sheet': typeof OrgSlugReportsBalanceSheetRoute
  '/$orgSlug/reports/daily-collections': typeof OrgSlugReportsDailyCollectionsRoute
  '/$orgSlug/reports/gst': typeof OrgSlugReportsGstRoute
  '/$orgSlug/reports/opd-register': typeof OrgSlugReportsOpdRegisterRoute
  '/$orgSlug/reports/trial-balance': typeof OrgSlugReportsTrialBalanceRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/catalog': typeof OrgSlugSettingsCatalogRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/staff': typeof OrgSlugSettingsStaffRoute
  '/$orgSlug/billing': typeof OrgSlugBillingIndexRoute
  '/$orgSlug/opd': typeof OrgSlugOpdIndexRoute
  '/$orgSlug/patients': typeof OrgSlugPatientsIndexRoute
  '/$orgSlug/reports': typeof OrgSlugReportsIndexRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/billing/invoices/$invoiceId': typeof OrgSlugBillingInvoicesInvoiceIdRouteWithChildren
  '/$orgSlug/opd/$appointmentId/billing': typeof OrgSlugOpdAppointmentIdBillingRoute
  '/$orgSlug/opd/$appointmentId': typeof OrgSlugOpdAppointmentIdIndexRoute
  '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId': typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId': typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId': typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute
  '/api/$orgSlug/billing/invoices/$invoiceId/pdf': typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteRouteWithChildren
  '/$orgSlug/dashboard': typeof OrgSlugDashboardRoute
  '/$orgSlug/files': typeof OrgSlugFilesRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/opd/$appointmentId': typeof OrgSlugOpdAppointmentIdRouteRouteWithChildren
  '/$orgSlug/opd/new': typeof OrgSlugOpdNewRoute
  '/$orgSlug/patients/$patientId': typeof OrgSlugPatientsPatientIdRoute
  '/$orgSlug/reports/balance-sheet': typeof OrgSlugReportsBalanceSheetRoute
  '/$orgSlug/reports/daily-collections': typeof OrgSlugReportsDailyCollectionsRoute
  '/$orgSlug/reports/gst': typeof OrgSlugReportsGstRoute
  '/$orgSlug/reports/opd-register': typeof OrgSlugReportsOpdRegisterRoute
  '/$orgSlug/reports/trial-balance': typeof OrgSlugReportsTrialBalanceRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/catalog': typeof OrgSlugSettingsCatalogRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/staff': typeof OrgSlugSettingsStaffRoute
  '/$orgSlug/billing/': typeof OrgSlugBillingIndexRoute
  '/$orgSlug/opd/': typeof OrgSlugOpdIndexRoute
  '/$orgSlug/patients/': typeof OrgSlugPatientsIndexRoute
  '/$orgSlug/reports/': typeof OrgSlugReportsIndexRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/billing/invoices/$invoiceId': typeof OrgSlugBillingInvoicesInvoiceIdRouteWithChildren
  '/$orgSlug/opd/$appointmentId/billing': typeof OrgSlugOpdAppointmentIdBillingRoute
  '/$orgSlug/opd/$appointmentId/': typeof OrgSlugOpdAppointmentIdIndexRoute
  '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId': typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId': typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId': typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute
  '/api/$orgSlug/billing/invoices/$invoiceId/pdf': typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/create'
    | '/join'
    | '/login'
    | '/$orgSlug/settings'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/files'
    | '/$orgSlug/onboarding'
    | '/$orgSlug/'
    | '/$orgSlug/opd/$appointmentId'
    | '/$orgSlug/opd/new'
    | '/$orgSlug/patients/$patientId'
    | '/$orgSlug/reports/balance-sheet'
    | '/$orgSlug/reports/daily-collections'
    | '/$orgSlug/reports/gst'
    | '/$orgSlug/reports/opd-register'
    | '/$orgSlug/reports/trial-balance'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/catalog'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/staff'
    | '/$orgSlug/billing/'
    | '/$orgSlug/opd/'
    | '/$orgSlug/patients/'
    | '/$orgSlug/reports/'
    | '/$orgSlug/settings/'
    | '/$orgSlug/billing/invoices/$invoiceId'
    | '/$orgSlug/opd/$appointmentId/billing'
    | '/$orgSlug/opd/$appointmentId/'
    | '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId'
    | '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId'
    | '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId'
    | '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/join'
    | '/login'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/files'
    | '/$orgSlug/onboarding'
    | '/$orgSlug'
    | '/$orgSlug/opd/new'
    | '/$orgSlug/patients/$patientId'
    | '/$orgSlug/reports/balance-sheet'
    | '/$orgSlug/reports/daily-collections'
    | '/$orgSlug/reports/gst'
    | '/$orgSlug/reports/opd-register'
    | '/$orgSlug/reports/trial-balance'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/catalog'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/staff'
    | '/$orgSlug/billing'
    | '/$orgSlug/opd'
    | '/$orgSlug/patients'
    | '/$orgSlug/reports'
    | '/$orgSlug/settings'
    | '/$orgSlug/billing/invoices/$invoiceId'
    | '/$orgSlug/opd/$appointmentId/billing'
    | '/$orgSlug/opd/$appointmentId'
    | '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId'
    | '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId'
    | '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId'
    | '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/create'
    | '/join'
    | '/login'
    | '/$orgSlug/settings'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/files'
    | '/$orgSlug/onboarding'
    | '/$orgSlug/'
    | '/$orgSlug/opd/$appointmentId'
    | '/$orgSlug/opd/new'
    | '/$orgSlug/patients/$patientId'
    | '/$orgSlug/reports/balance-sheet'
    | '/$orgSlug/reports/daily-collections'
    | '/$orgSlug/reports/gst'
    | '/$orgSlug/reports/opd-register'
    | '/$orgSlug/reports/trial-balance'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/catalog'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/staff'
    | '/$orgSlug/billing/'
    | '/$orgSlug/opd/'
    | '/$orgSlug/patients/'
    | '/$orgSlug/reports/'
    | '/$orgSlug/settings/'
    | '/$orgSlug/billing/invoices/$invoiceId'
    | '/$orgSlug/opd/$appointmentId/billing'
    | '/$orgSlug/opd/$appointmentId/'
    | '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId'
    | '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId'
    | '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId'
    | '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute: typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/dashboard': {
      id: '/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$orgSlug/dashboard'
      preLoaderRoute: typeof OrgSlugDashboardRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/files': {
      id: '/$orgSlug/files'
      path: '/files'
      fullPath: '/$orgSlug/files'
      preLoaderRoute: typeof OrgSlugFilesRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/onboarding': {
      id: '/$orgSlug/onboarding'
      path: '/onboarding'
      fullPath: '/$orgSlug/onboarding'
      preLoaderRoute: typeof OrgSlugOnboardingRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/billing/': {
      id: '/$orgSlug/billing/'
      path: '/billing'
      fullPath: '/$orgSlug/billing/'
      preLoaderRoute: typeof OrgSlugBillingIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/opd/': {
      id: '/$orgSlug/opd/'
      path: '/opd'
      fullPath: '/$orgSlug/opd/'
      preLoaderRoute: typeof OrgSlugOpdIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/opd/$appointmentId': {
      id: '/$orgSlug/opd/$appointmentId'
      path: '/opd/$appointmentId'
      fullPath: '/$orgSlug/opd/$appointmentId'
      preLoaderRoute: typeof OrgSlugOpdAppointmentIdRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/opd/new': {
      id: '/$orgSlug/opd/new'
      path: '/opd/new'
      fullPath: '/$orgSlug/opd/new'
      preLoaderRoute: typeof OrgSlugOpdNewRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/patients/': {
      id: '/$orgSlug/patients/'
      path: '/patients'
      fullPath: '/$orgSlug/patients/'
      preLoaderRoute: typeof OrgSlugPatientsIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/patients/$patientId': {
      id: '/$orgSlug/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/$orgSlug/patients/$patientId'
      preLoaderRoute: typeof OrgSlugPatientsPatientIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/': {
      id: '/$orgSlug/reports/'
      path: '/reports'
      fullPath: '/$orgSlug/reports/'
      preLoaderRoute: typeof OrgSlugReportsIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/balance-sheet': {
      id: '/$orgSlug/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/$orgSlug/reports/balance-sheet'
      preLoaderRoute: typeof OrgSlugReportsBalanceSheetRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/daily-collections': {
      id: '/$orgSlug/reports/daily-collections'
      path: '/reports/daily-collections'
      fullPath: '/$orgSlug/reports/daily-collections'
      preLoaderRoute: typeof OrgSlugReportsDailyCollectionsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/gst': {
      id: '/$orgSlug/reports/gst'
      path: '/reports/gst'
      fullPath: '/$orgSlug/reports/gst'
      preLoaderRoute: typeof OrgSlugReportsGstRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/opd-register': {
      id: '/$orgSlug/reports/opd-register'
      path: '/reports/opd-register'
      fullPath: '/$orgSlug/reports/opd-register'
      preLoaderRoute: typeof OrgSlugReportsOpdRegisterRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/trial-balance': {
      id: '/$orgSlug/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/$orgSlug/reports/trial-balance'
      preLoaderRoute: typeof OrgSlugReportsTrialBalanceRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/audit': {
      id: '/$orgSlug/settings/audit'
      path: '/audit'
      fullPath: '/$orgSlug/settings/audit'
      preLoaderRoute: typeof OrgSlugSettingsAuditRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/catalog': {
      id: '/$orgSlug/settings/catalog'
      path: '/catalog'
      fullPath: '/$orgSlug/settings/catalog'
      preLoaderRoute: typeof OrgSlugSettingsCatalogRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/members': {
      id: '/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/$orgSlug/settings/members'
      preLoaderRoute: typeof OrgSlugSettingsMembersRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/organization': {
      id: '/$orgSlug/settings/organization'
      path: '/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof OrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/staff': {
      id: '/$orgSlug/settings/staff'
      path: '/staff'
      fullPath: '/$orgSlug/settings/staff'
      preLoaderRoute: typeof OrgSlugSettingsStaffRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/billing/invoices/$invoiceId': {
      id: '/$orgSlug/billing/invoices/$invoiceId'
      path: '/billing/invoices/$invoiceId'
      fullPath: '/$orgSlug/billing/invoices/$invoiceId'
      preLoaderRoute: typeof OrgSlugBillingInvoicesInvoiceIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/opd/$appointmentId/': {
      id: '/$orgSlug/opd/$appointmentId/'
      path: '/'
      fullPath: '/$orgSlug/opd/$appointmentId/'
      preLoaderRoute: typeof OrgSlugOpdAppointmentIdIndexRouteImport
      parentRoute: typeof OrgSlugOpdAppointmentIdRouteRoute
    }
    '/$orgSlug/opd/$appointmentId/billing': {
      id: '/$orgSlug/opd/$appointmentId/billing'
      path: '/billing'
      fullPath: '/$orgSlug/opd/$appointmentId/billing'
      preLoaderRoute: typeof OrgSlugOpdAppointmentIdBillingRouteImport
      parentRoute: typeof OrgSlugOpdAppointmentIdRouteRoute
    }
    '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId': {
      id: '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId'
      path: '/credit-note/$creditNoteId'
      fullPath: '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId'
      preLoaderRoute: typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRouteImport
      parentRoute: typeof OrgSlugBillingInvoicesInvoiceIdRoute
    }
    '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId': {
      id: '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId'
      path: '/receipt/$paymentId'
      fullPath: '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId'
      preLoaderRoute: typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRouteImport
      parentRoute: typeof OrgSlugBillingInvoicesInvoiceIdRoute
    }
    '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId': {
      id: '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId'
      path: '/refund/$refundId'
      fullPath: '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId'
      preLoaderRoute: typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRouteImport
      parentRoute: typeof OrgSlugBillingInvoicesInvoiceIdRoute
    }
    '/api/$orgSlug/billing/invoices/$invoiceId/pdf': {
      id: '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
      path: '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
      fullPath: '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
      preLoaderRoute: typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrgSlugSettingsRouteRouteChildren {
  OrgSlugSettingsAuditRoute: typeof OrgSlugSettingsAuditRoute
  OrgSlugSettingsCatalogRoute: typeof OrgSlugSettingsCatalogRoute
  OrgSlugSettingsMembersRoute: typeof OrgSlugSettingsMembersRoute
  OrgSlugSettingsOrganizationRoute: typeof OrgSlugSettingsOrganizationRoute
  OrgSlugSettingsStaffRoute: typeof OrgSlugSettingsStaffRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugSettingsRouteRouteChildren: OrgSlugSettingsRouteRouteChildren = {
  OrgSlugSettingsAuditRoute: OrgSlugSettingsAuditRoute,
  OrgSlugSettingsCatalogRoute: OrgSlugSettingsCatalogRoute,
  OrgSlugSettingsMembersRoute: OrgSlugSettingsMembersRoute,
  OrgSlugSettingsOrganizationRoute: OrgSlugSettingsOrganizationRoute,
  OrgSlugSettingsStaffRoute: OrgSlugSettingsStaffRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugSettingsRouteRouteWithChildren =
  OrgSlugSettingsRouteRoute._addFileChildren(OrgSlugSettingsRouteRouteChildren)

interface OrgSlugOpdAppointmentIdRouteRouteChildren {
  OrgSlugOpdAppointmentIdBillingRoute: typeof OrgSlugOpdAppointmentIdBillingRoute
  OrgSlugOpdAppointmentIdIndexRoute: typeof OrgSlugOpdAppointmentIdIndexRoute
}

const OrgSlugOpdAppointmentIdRouteRouteChildren: OrgSlugOpdAppointmentIdRouteRouteChildren =
  {
    OrgSlugOpdAppointmentIdBillingRoute: OrgSlugOpdAppointmentIdBillingRoute,
    OrgSlugOpdAppointmentIdIndexRoute: OrgSlugOpdAppointmentIdIndexRoute,
  }

const OrgSlugOpdAppointmentIdRouteRouteWithChildren =
  OrgSlugOpdAppointmentIdRouteRoute._addFileChildren(
    OrgSlugOpdAppointmentIdRouteRouteChildren,
  )

interface OrgSlugBillingInvoicesInvoiceIdRouteChildren {
  OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute: typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute
  OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute: typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute
  OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute: typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute
}

const OrgSlugBillingInvoicesInvoiceIdRouteChildren: OrgSlugBillingInvoicesInvoiceIdRouteChildren =
  {
    OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute:
      OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute,
    OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute:
      OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute,
    OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute:
      OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute,
  }

const OrgSlugBillingInvoicesInvoiceIdRouteWithChildren =
  OrgSlugBillingInvoicesInvoiceIdRoute._addFileChildren(
    OrgSlugBillingInvoicesInvoiceIdRouteChildren,
  )

interface OrgSlugRouteRouteChildren {
  OrgSlugSettingsRouteRoute: typeof OrgSlugSettingsRouteRouteWithChildren
  OrgSlugDashboardRoute: typeof OrgSlugDashboardRoute
  OrgSlugFilesRoute: typeof OrgSlugFilesRoute
  OrgSlugOnboardingRoute: typeof OrgSlugOnboardingRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugOpdAppointmentIdRouteRoute: typeof OrgSlugOpdAppointmentIdRouteRouteWithChildren
  OrgSlugOpdNewRoute: typeof OrgSlugOpdNewRoute
  OrgSlugPatientsPatientIdRoute: typeof OrgSlugPatientsPatientIdRoute
  OrgSlugReportsBalanceSheetRoute: typeof OrgSlugReportsBalanceSheetRoute
  OrgSlugReportsDailyCollectionsRoute: typeof OrgSlugReportsDailyCollectionsRoute
  OrgSlugReportsGstRoute: typeof OrgSlugReportsGstRoute
  OrgSlugReportsOpdRegisterRoute: typeof OrgSlugReportsOpdRegisterRoute
  OrgSlugReportsTrialBalanceRoute: typeof OrgSlugReportsTrialBalanceRoute
  OrgSlugBillingIndexRoute: typeof OrgSlugBillingIndexRoute
  OrgSlugOpdIndexRoute: typeof OrgSlugOpdIndexRoute
  OrgSlugPatientsIndexRoute: typeof OrgSlugPatientsIndexRoute
  OrgSlugReportsIndexRoute: typeof OrgSlugReportsIndexRoute
  OrgSlugBillingInvoicesInvoiceIdRoute: typeof OrgSlugBillingInvoicesInvoiceIdRouteWithChildren
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugSettingsRouteRoute: OrgSlugSettingsRouteRouteWithChildren,
  OrgSlugDashboardRoute: OrgSlugDashboardRoute,
  OrgSlugFilesRoute: OrgSlugFilesRoute,
  OrgSlugOnboardingRoute: OrgSlugOnboardingRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugOpdAppointmentIdRouteRoute:
    OrgSlugOpdAppointmentIdRouteRouteWithChildren,
  OrgSlugOpdNewRoute: OrgSlugOpdNewRoute,
  OrgSlugPatientsPatientIdRoute: OrgSlugPatientsPatientIdRoute,
  OrgSlugReportsBalanceSheetRoute: OrgSlugReportsBalanceSheetRoute,
  OrgSlugReportsDailyCollectionsRoute: OrgSlugReportsDailyCollectionsRoute,
  OrgSlugReportsGstRoute: OrgSlugReportsGstRoute,
  OrgSlugReportsOpdRegisterRoute: OrgSlugReportsOpdRegisterRoute,
  OrgSlugReportsTrialBalanceRoute: OrgSlugReportsTrialBalanceRoute,
  OrgSlugBillingIndexRoute: OrgSlugBillingIndexRoute,
  OrgSlugOpdIndexRoute: OrgSlugOpdIndexRoute,
  OrgSlugPatientsIndexRoute: OrgSlugPatientsIndexRoute,
  OrgSlugReportsIndexRoute: OrgSlugReportsIndexRoute,
  OrgSlugBillingInvoicesInvoiceIdRoute:
    OrgSlugBillingInvoicesInvoiceIdRouteWithChildren,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute:
    ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
