import { Button } from "@hms/ui/components/button";
import { Sheet, SheetContent, SheetTitle } from "@hms/ui/components/sheet";
import { cn } from "@hms/ui/lib/utils";
import { ClientOnly, useBlocker } from "@tanstack/react-router";
import { XIcon } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";

import { useConfirm } from "@/components/confirm-dialog";
import { PatientForm, type EditablePatient } from "@/components/patient-form";

/**
 * A patient record as a panel over whatever the operator was looking at, rather
 * than a page away from it: they keep their place, and the list or the record
 * behind refreshes under the sheet as soon as it saves.
 *
 * One sheet serves both jobs. The sheet owns only opening and closing;
 * `PatientForm` owns the record, and switches between registering and
 * correcting based on whether it was handed one.
 */

/**
 * Geometry only. The motion — a 2.5rem slide with an opacity fade over 200ms,
 * behind a `bg-black/10` scrim — is `SheetContent`'s own and is deliberately
 * left alone: ReUI's sheet, read off their live page, resolves to exactly these
 * values, so the default already is the reference.
 *
 * The classes carry the `data-[side=right]:` prefix because that is the prefix
 * `SheetContent` uses for its own geometry, and an unprefixed class loses to
 * it. If a second sheet ever needs a different size, that belongs in the
 * component as a variant rather than as a second copy of this block.
 */
const PANEL = cn(
  // Below `md` the panel is the page. A 520px sheet on a phone is a modal
  // pretending to be a sheet.
  "data-[side=right]:inset-0 data-[side=right]:h-full data-[side=right]:w-full",
  "data-[side=right]:border-l-0 data-[side=right]:sm:max-w-none",
  // From `md` up it floats clear of the edges.
  "data-[side=right]:md:inset-y-4 data-[side=right]:md:right-4 data-[side=right]:md:left-auto",
  "data-[side=right]:md:h-auto data-[side=right]:md:w-[520px]",
  "data-[side=right]:md:rounded-lg data-[side=right]:md:border",
  // The form supplies its own padding per region, so the panel supplies none.
  "gap-0 p-0",
);

export function PatientSheet({
  orgSlug,
  patient,
  open,
  onOpenChange,
}: {
  orgSlug: string;
  /** Omit to register a new patient; pass a record to correct an existing one. */
  patient?: EditablePatient;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const [dirty, setDirty] = useState(false);
  const [pending, setPending] = useState(false);
  const [confirm, confirmation] = useConfirm();
  const bypassBlocker = useRef(false);
  const blocker = useBlocker({
    shouldBlockFn: () => dirty && !bypassBlocker.current,
    enableBeforeUnload: dirty,
    disabled: !dirty,
    withResolver: true,
  });

  const closeWithoutBlocking = useCallback(() => {
    bypassBlocker.current = true;
    setDirty(false);
    onOpenChange(false);
    window.setTimeout(() => {
      bypassBlocker.current = false;
    }, 0);
  }, [onOpenChange]);

  useEffect(() => {
    if (blocker.status !== "blocked") return;
    confirm({
      title: "Discard unsaved changes?",
      description: "The patient record has changes that have not been saved.",
      confirmLabel: "Discard changes",
      run: () => {
        setDirty(false);
        blocker.proceed();
      },
      cancel: blocker.reset,
    });
  }, [blocker, confirm]);

  const close = useCallback(() => {
    if (pending) return;

    if (!dirty) {
      closeWithoutBlocking();
      return;
    }

    confirm({
      title: "Discard unsaved changes?",
      description: "The patient record has changes that have not been saved.",
      confirmLabel: "Discard changes",
      run: closeWithoutBlocking,
    });
  }, [closeWithoutBlocking, confirm, dirty, pending]);

  const saved = useCallback(() => closeWithoutBlocking(), [closeWithoutBlocking]);

  return (
    <>
      <ClientOnly fallback={null}>
        <Sheet open={open} onOpenChange={(nextOpen) => (nextOpen ? onOpenChange(true) : close())}>
          <SheetContent
            className={PANEL}
            showCloseButton={false}
            // Without this the sheet opens with the close button focused, because
            // it is the first focusable element in the panel. The field ids are
            // generated by `FormItem`, so the first input is the reliable target.
            initialFocus={() =>
              document.querySelector<HTMLElement>("[data-slot=sheet-content] input")
            }
          >
            <header className="flex shrink-0 items-center gap-3 border-b border-border p-4">
              <SheetTitle>{patient ? "Edit patient" : "Register patient"}</SheetTitle>
              <Button
                type="button"
                variant="ghost"
                size="icon-sm"
                className="ml-auto"
                onClick={close}
                disabled={pending}
              >
                <XIcon />
                <span className="sr-only">Close</span>
              </Button>
            </header>
            <PatientForm
              key={`${patient?.id ?? "new"}:${open ? "open" : "closed"}`}
              orgSlug={orgSlug}
              patient={patient}
              onCancel={close}
              onSaved={saved}
              onDirtyChange={setDirty}
              onPendingChange={setPending}
            />
          </SheetContent>
        </Sheet>
      </ClientOnly>
      {confirmation}
    </>
  );
}
